# Generated by Django 2.1.7 on 2019-04-29 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(default='', max_length=200)),
                ('nota_trabalho', models.IntegerField(default=-1)),
                ('nota_final', models.IntegerField(default=-1)),
                ('ultima_semana', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(default=-1)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Ficheiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ficheiro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Miniteste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao_texto', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicacao')),
            ],
        ),
        migrations.CreateModel(
            name='QuestaoMT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_questo', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicacao')),
                ('miniteste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.Miniteste')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.CharField(max_length=200)),
                ('resposta_dono', models.CharField(max_length=200)),
                ('resposta_pub_data', models.DateTimeField(verbose_name='data de publicacao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.Questao')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaMT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.CharField(max_length=200)),
                ('resposta_certa', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.QuestaoMT')),
            ],
        ),
        migrations.CreateModel(
            name='SlidePasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pasta', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ficheiro',
            name='slidepasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.SlidePasta'),
        ),
    ]
