# Generated by Django 2.1.7 on 2019-05-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0008_questao_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='data de avalição')),
                ('sala', models.CharField(max_length=10)),
                ('descrição', models.CharField(max_length=200)),
            ],
        ),
    ]
