# Generated by Django 2.1.7 on 2019-04-29 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0002_auto_20190429_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_denunciante', models.CharField(max_length=200)),
                ('data', models.DateTimeField(verbose_name='data de denuncia')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.Questao')),
            ],
        ),
    ]
