# Generated by Django 2.1.7 on 2019-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0003_denuncia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='questao',
        ),
        migrations.AddField(
            model_name='questao',
            name='denuncias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resposta',
            name='denuncias',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Denuncia',
        ),
    ]
