# Generated by Django 2.1.7 on 2019-05-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0005_denuncia_pasta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='denuncias',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='denuncias',
        ),
    ]
