# Generated by Django 2.1.7 on 2019-05-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0007_denuncia_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
