# Generated by Django 2.1.7 on 2019-05-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0011_auto_20190514_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
